### PR TITLE
Created a script locustfilegenerator to generate draft locust files.

### PR DESCRIPTION
**Pull request by foolchan2556**
locustfilegenerator.py is a script to grab our django project's apis and create testing functions automatically. We can add annotation such as @task(1) to enable a set of functions for locust. locustDemo.py is a sample generated by this script.

I will refine it later and build some benchmark scripts with that. And I hope this script will help a little.

### CODE REVIEW

**Comment by aronasorman** [comment]
How do I run this?

**Comment by foolchan2556** [comment]
Just configure the locustfilegenerator script to your environment, and run it.

**Comment by foolchan2556** [comment]
So whenever our api changes, we can always get the latest benchmark script draft.

**Comment by foolchan2556** [comment]
Hi @aronasorman , the locust file is added as the watch a video.py. I will try to benchmark on loading the whole page. Have a good day!

**Pull request closed without merging**
